version: '3.8'

services:
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    hostname: rabbitserver
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
